### PR TITLE
Migrate to dotnet core 2.0

### PR DESCRIPTION
**Pull request by sbalant**
I migrated the two project to dotnet core 2.0
Need vs 2017 or vs code with dotnet core 2.0 sdk (https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-download.md)

### CODE REVIEW

**Comment by David-Desmaisons** [comment]
@sbalant Thanks for your contribution. I will have to figure out how to have a project building for bioth .Net Core and .Net with build OK.

**Comment by 4nonym0us** [comment]
+1 to the migration request. Would be great to see .NET Standard as a target framework.
@sbalant  I have a question about target frameworks in this PR (`<TargetFrameworks>netstandard2.0;net461</TargetFrameworks>`). Multiple targeting net461 makes no sense unless there is .NET Framework dependent code and library seems to be fully compatible with .NET Standard specification.
@David-Desmaisons will you have a time to review the PR in foreseeable future?

**Comment by David-Desmaisons** [comment]
Hello @4nonym0us , the idea is to migrate to have a library targeting diferent runtimes and not only .NetCore as this is the case currently with this PR.
 I currently don't have time to make the changes, but I will review and accept such PR.

**Comment by 4nonym0us** [comment]
I'm not sure if you understand the difference between targeting .NET Core and .NET Standard. .NET Core is a framework for applications, while .NET Standard is specification. Thus means if you target .NET Standard in your library then you are targeting ALL of the modern frameworks (including .NET Framework, .NET Core, Mono, multiple Xamarin Framwork and etc. (Take a look at https://docs.microsoft.com/en-us/dotnet/standard/net-standard to see what .NET Standard covers).

To sum up, he difference is following: if you target .NET Core then only .NET Core application would be able to use your library, but if you target .NET Standard then your library will be compatible with .NET Framework, Mono, Xamarin, etc. The only reason to set the multiple explicit target platforms is when your library require API, which is not available on other platforms i.e. GPS API on UWM, GPS API on Xamarin, specific Windows-only API, etc (in this case you should use preproccessor directives to use specific API and build a project for each of the platform). As far as I see, there is no such a dependencies in RateLimiter and I asked the question to warn you.

**Comment by sbalant** [comment]
Hello @4nonym0us,
I specify the target net461 in the project RateLimiter to be able to install the package in a net461 web application
If I don't do that, I've got this error 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'RateLimiter 1.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.	
```

**Comment by 4nonym0us** [comment]
@sbalant It depends on .NET Framework version and .NET Standard version. .NET Standard 1.0 is supported by .NET Framework 4.5 and above while .NET Standard 2.0 is supported by .NET Framework 4.6.1 and above.
Microsoft recommends following:
> So generally speaking, you should target the lowest version you get away with. To inform your decision, you should consider the compatibility matrix and the APIs additions linked from the table above.

So the first issue is that there is no need to target .NET Standard 2.0 since RateLimiter is compatible with with .NET Standard 1.0. And if you target lower version of .NET Standard you will get the library running on .NET Framework 4.5 and above.

**Comment by David-Desmaisons** [comment]
@4nonym0us Could you create the corresponding PR?

**Comment by 4nonym0us** [comment]
@David-Desmaisons sure, I'll do it soon.

**Comment by gentisaliu** [comment]
+1 I need a .NET Core 2 port as well.

**Comment by David-Desmaisons** [comment]
@sbalant , Thanks for the contribution update to .NET standard has been made.

**Pull request closed without merging**
