### PR TITLE
Await on TimeLimiter

### PR DESCRIPTION
**Pull request by gioccher**
Allows awaiting on the TimeLimiter object, making it less awkward to use when the code that needs to be rate limited contains other code that needs to be rate limited.

See https://github.com/David-Desmaisons/RateLimiter/issues/12

Usage:
```
    var timeconstraint = TimeLimiter.GetFromMaxCountByInterval(5, TimeSpan.FromSeconds(1));
    for(int i=0; i<1000; i++)
    {
        await timeconstraint;
        Trace.WriteLine(string.Format("{0:MM/dd/yyy HH:mm:ss.fff}", DateTime.Now));
    }
```

### CODE REVIEW

**Comment by David-Desmaisons** [comment]
Thanks for the PR, I made some comments regarding the current implementation

**Comment by gioccher** [comment]
I'm sorry, I feel totally lost. Where can I find your comments?
I now see that codecov is complaining about a decrease in test coverage (the bot posted that notice after I left this page, and I never received a notification), but I don't see the comments you are mentioning

**Comment by David-Desmaisons** [comment]
@gioccher It seems tat I forgot to press the "submit review" button. Sorry for that. You can now find the correspoding comments.

**Comment by David-Desmaisons** [comment]
This feature is now implemented in version v2.0.0

**Pull request closed without merging**
